### ISSUE TITLE
icons werden nach Adapterinstallation nicht angezeigt, Installationsordner bleibt leer.

### ISSUE THREAD

**Issue by Viruswelt** [ioBroker/ioBroker.icons-mfd-png#1]
Nach der Adapterinstallation können keine Icons ausgewählt werden, es existiert nur der icons-mfd-png.admin Ordner (gleiches gilt für die svg Variante)
Getestet auf einem frisch aufgesetzten ioBroker.
Keine Auffälligkeiten im Log.

![icons-mfd-png](https://cloud.githubusercontent.com/assets/22518874/21658737/02a3eb5e-d2c8-11e6-9f9d-9fd435ed6267.jpeg)
![log](https://cloud.githubusercontent.com/assets/22518874/21658902/9d291f50-d2c8-11e6-8f6e-c85795473125.jpeg)
![datei manager](https://cloud.githubusercontent.com/assets/22518874/21659092/6c4ae0ac-d2c9-11e6-8032-db6a635593b4.jpeg)

**Comment by Apollon77** [comment]
Also bei mir liegen die in /icons-mfd-svg/ wenn ich in den Dateimanager gehe ...
In der Normalen Verzeichnisstrukturliegen Sie nicht. Aber hast Recht bei der 1.0.1 passt irgendwas nicht. Gebe es weiter

**Comment by Viruswelt** [comment]
Mit 1.0.2 funktioniert alles, Danke !!
