### ISSUE TITLE
Update stable version in repo from 1.1.0 to 1.2.1

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.icons-mfd-png#10]
# Think about update stable version to 1.2.1
**Version**: stable=**1.1.0** (621 days old) => latest=**1.2.1** (15 days old)
**Installs**: stable=**7480** (83.28%), latest=**816** (9.08%), total=**8982**

Click to use [developer portal](https://www.iobroker.dev/adapter/icons-mfd-png/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1079)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
@Apollon77 
@GermanBluefox 

Any reason to delay stable update any longer?

**If there's no reaction / comment until 7.1.2024 an update will be considered anyway.**

**Comment by Apollon77** [comment]
icon adapter ... always do :-)

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.2.1 but the current stable version is already 1.2.1.

So this issue should be closed.
